//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArabicTextAnalyzer.Content.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class R {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal R() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArabicTextAnalyzer.Content.Resources.R", typeof(R).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config FB Alerts.
        /// </summary>
        public static string ConfigFBAlerts {
            get {
                return ResourceManager.GetString("ConfigFBAlerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook Pages.
        /// </summary>
        public static string FacebookPages {
            get {
                return ResourceManager.GetString("FacebookPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in Gravitas App.
        /// </summary>
        public static string LogInGravitasApp {
            get {
                return ResourceManager.GetString("LogInGravitasApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Date.
        /// </summary>
        public static string PostDate {
            get {
                return ResourceManager.GetString("PostDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me ?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve new posts.
        /// </summary>
        public static string RetrieveNewPosts {
            get {
                return ResourceManager.GetString("RetrieveNewPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show statistics about extracted entities from your theme&apos;s data.
        /// </summary>
        public static string ShowStatisticsAboutEtc {
            get {
                return ResourceManager.GetString("ShowStatisticsAboutEtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stats &amp; Reports.
        /// </summary>
        public static string StatsNdReports {
            get {
                return ResourceManager.GetString("StatsNdReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate Arabizi.
        /// </summary>
        public static string TranslateArabizi {
            get {
                return ResourceManager.GetString("TranslateArabizi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate Arabizi to Arabic and extract entities.
        /// </summary>
        public static string TranslateArabiziToArabicEtc {
            get {
                return ResourceManager.GetString("TranslateArabiziToArabicEtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translated Post.
        /// </summary>
        public static string TranslatedPost {
            get {
                return ResourceManager.GetString("TranslatedPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Arabizi Text, and click Go ....
        /// </summary>
        public static string TypeArabiziTextAndClickGo {
            get {
                return ResourceManager.GetString("TypeArabiziTextAndClickGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a local account to log in..
        /// </summary>
        public static string UseALocalAccountToLogIn {
            get {
                return ResourceManager.GetString("UseALocalAccountToLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Facebook pages as data source to translate Arabizi and extract entities.
        /// </summary>
        public static string UseFacebookPagesEtc {
            get {
                return ResourceManager.GetString("UseFacebookPagesEtc", resourceCulture);
            }
        }
    }
}
