//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArabicTextAnalyzer.Content.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class R {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal R() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArabicTextAnalyzer.Content.Resources.R", typeof(R).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new influencer.
        /// </summary>
        public static string AddNewFBPage {
            get {
                return ResourceManager.GetString("AddNewFBPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new theme.
        /// </summary>
        public static string AddNewTheme {
            get {
                return ResourceManager.GetString("AddNewTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        public static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabizi.
        /// </summary>
        public static string Arabizi {
            get {
                return ResourceManager.GetString("Arabizi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the theme.
        /// </summary>
        public static string AreYouSureYouWantToDeleteTheTheme {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToDeleteTheTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your email and confirm your account, you must be confirmed before you can log in..
        /// </summary>
        public static string CheckYourMailAndConfirmEtc {
            get {
                return ResourceManager.GetString("CheckYourMailAndConfirmEtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to Log in.
        /// </summary>
        public static string ClickHereToLogIn {
            get {
                return ResourceManager.GetString("ClickHereToLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma-separated target entities : coca-cola, fanta, ....
        /// </summary>
        public static string CommaSeparatedTargetEntitiesEtc {
            get {
                return ResourceManager.GetString("CommaSeparatedTargetEntitiesEtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config FB Alerts.
        /// </summary>
        public static string ConfigFBAlerts {
            get {
                return ResourceManager.GetString("ConfigFBAlerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed Email.
        /// </summary>
        public static string ConfirmedEmail {
            get {
                return ResourceManager.GetString("ConfirmedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Theme Deletion.
        /// </summary>
        public static string ConfirmThemeDeletion {
            get {
                return ResourceManager.GetString("ConfirmThemeDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumption.
        /// </summary>
        public static string Consumption {
            get {
                return ResourceManager.GetString("Consumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your account.
        /// </summary>
        public static string CreateANewAccount {
            get {
                return ResourceManager.GetString("CreateANewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily consumption exceeded.
        /// </summary>
        public static string DailyConsumptionExceeded {
            get {
                return ResourceManager.GetString("DailyConsumptionExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit active theme.
        /// </summary>
        public static string EditActiveTheme {
            get {
                return ResourceManager.GetString("EditActiveTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Link.
        /// </summary>
        public static string EmailLink {
            get {
                return ResourceManager.GetString("EmailLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new theme name.
        /// </summary>
        public static string EnterNewThemeName {
            get {
                return ResourceManager.GetString("EnterNewThemeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter page name : ex : RajaClubAthleticOfficiel.
        /// </summary>
        public static string EnterPageName {
            get {
                return ResourceManager.GetString("EnterPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter theme new name.
        /// </summary>
        public static string EnterThemeNewName {
            get {
                return ResourceManager.GetString("EnterThemeNewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email..
        /// </summary>
        public static string EnterYourEmail {
            get {
                return ResourceManager.GetString("EnterYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entities.
        /// </summary>
        public static string Entities {
            get {
                return ResourceManager.GetString("Entities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook Pages.
        /// </summary>
        public static string FacebookPages {
            get {
                return ResourceManager.GetString("FacebookPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FaceBook Page Alerts / Filters Settings.
        /// </summary>
        public static string FBPageAlertsSlashFiltersSettings {
            get {
                return ResourceManager.GetString("FBPageAlertsSlashFiltersSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FB Page Name.
        /// </summary>
        public static string FBPageName {
            get {
                return ResourceManager.GetString("FBPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password Confirmation.
        /// </summary>
        public static string ForgotPasswordConfirmation {
            get {
                return ResourceManager.GetString("ForgotPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string ForgotYourPassword {
            get {
                return ResourceManager.GetString("ForgotYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        public static string here {
            get {
                return ResourceManager.GetString("here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        public static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login attempt..
        /// </summary>
        public static string InvalidLoginAttempt {
            get {
                return ResourceManager.GetString("InvalidLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in Gravitas App.
        /// </summary>
        public static string LogInGravitasApp {
            get {
                return ResourceManager.GetString("LogInGravitasApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your account settings.
        /// </summary>
        public static string ManageYourAccountSettings {
            get {
                return ResourceManager.GetString("ManageYourAccountSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NER Types.
        /// </summary>
        public static string NerTypes {
            get {
                return ResourceManager.GetString("NerTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Theme to Analyze.
        /// </summary>
        public static string NewThemeToAnalyze {
            get {
                return ResourceManager.GetString("NewThemeToAnalyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Not Found.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please.
        /// </summary>
        public static string Please {
            get {
                return ResourceManager.GetString("Please", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email to reset your password.
        /// </summary>
        public static string PleaseCheckYourEmailToResetEtc {
            get {
                return ResourceManager.GetString("PleaseCheckYourEmailToResetEtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please reset your password by clicking.
        /// </summary>
        public static string PleaseResetYourPasswordByClicking {
            get {
                return ResourceManager.GetString("PleaseResetYourPasswordByClicking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Date.
        /// </summary>
        public static string PostDate {
            get {
                return ResourceManager.GetString("PostDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Charts.
        /// </summary>
        public static string RefreshCharts {
            get {
                return ResourceManager.GetString("RefreshCharts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a new user.
        /// </summary>
        public static string RegisterAsANewUser {
            get {
                return ResourceManager.GetString("RegisterAsANewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register into Gravitas App.
        /// </summary>
        public static string RegisterIntoGravitasApp {
            get {
                return ResourceManager.GetString("RegisterIntoGravitasApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me ?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove active theme.
        /// </summary>
        public static string RemoveActiveTheme {
            get {
                return ResourceManager.GetString("RemoveActiveTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Theme.
        /// </summary>
        public static string RenameTheme {
            get {
                return ResourceManager.GetString("RenameTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password confirmation.
        /// </summary>
        public static string ResetPasswordConfirmation {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset your password..
        /// </summary>
        public static string ResetYourPassword {
            get {
                return ResourceManager.GetString("ResetYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve new posts.
        /// </summary>
        public static string RetrieveNewPosts {
            get {
                return ResourceManager.GetString("RetrieveNewPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Settings.
        /// </summary>
        public static string SaveSettings {
            get {
                return ResourceManager.GetString("SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for social data over Facebook content over Moroccan pages.
        /// </summary>
        public static string SearchForSocialDataEtc {
            get {
                return ResourceManager.GetString("SearchForSocialDataEtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show statistics about extracted entities from your theme&apos;s data.
        /// </summary>
        public static string ShowStatisticsAboutEtc {
            get {
                return ResourceManager.GetString("ShowStatisticsAboutEtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Search.
        /// </summary>
        public static string SocialSearch {
            get {
                return ResourceManager.GetString("SocialSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start/stop auto retrieve of FB posts and comments.
        /// </summary>
        public static string StartStopAutoRetrieveOfEtc {
            get {
                return ResourceManager.GetString("StartStopAutoRetrieveOfEtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stats &amp; Reports.
        /// </summary>
        public static string StatsNdReports {
            get {
                return ResourceManager.GetString("StatsNdReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Entities.
        /// </summary>
        public static string TargetEntities {
            get {
                return ResourceManager.GetString("TargetEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for confirming your email.
        /// </summary>
        public static string ThankYouForConfirmingYourEmail {
            get {
                return ResourceManager.GetString("ThankYouForConfirmingYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme Name.
        /// </summary>
        public static string ThemeName {
            get {
                return ResourceManager.GetString("ThemeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme New Name.
        /// </summary>
        public static string ThemeNewName {
            get {
                return ResourceManager.GetString("ThemeNewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROJECTS.
        /// </summary>
        public static string THEMES {
            get {
                return ResourceManager.GetString("THEMES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track your account Consumption.
        /// </summary>
        public static string TrackYourAccountConsumption {
            get {
                return ResourceManager.GetString("TrackYourAccountConsumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate Arabizi.
        /// </summary>
        public static string TranslateArabizi {
            get {
                return ResourceManager.GetString("TranslateArabizi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate Arabizi to Arabic and extract entities.
        /// </summary>
        public static string TranslateArabiziToArabicEtc {
            get {
                return ResourceManager.GetString("TranslateArabiziToArabicEtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate, display, filter, export, import data and extract insights from working data.
        /// </summary>
        public static string TranslateDisplayFilterEtc {
            get {
                return ResourceManager.GetString("TranslateDisplayFilterEtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translated Post.
        /// </summary>
        public static string TranslatedPost {
            get {
                return ResourceManager.GetString("TranslatedPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate / NER / SA.
        /// </summary>
        public static string TranslateNerSa {
            get {
                return ResourceManager.GetString("TranslateNerSa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Arabizi Text, and click Go ....
        /// </summary>
        public static string TypeArabiziTextAndClickGo {
            get {
                return ResourceManager.GetString("TypeArabiziTextAndClickGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a local account to log in..
        /// </summary>
        public static string UseALocalAccountToLogIn {
            get {
                return ResourceManager.GetString("UseALocalAccountToLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Facebook pages as data source to translate Arabizi and extract entities.
        /// </summary>
        public static string UseFacebookPagesEtc {
            get {
                return ResourceManager.GetString("UseFacebookPagesEtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset.
        /// </summary>
        public static string YourPasswordHasBeenReset {
            get {
                return ResourceManager.GetString("YourPasswordHasBeenReset", resourceCulture);
            }
        }
    }
}
