SELECT 
	COUNT(*) COUNTPOSITIVENER from T_ARABICDARIJAENTRY AR
	INNER JOIN T_ARABICDARIJAENTRY_TEXTENTITY TE ON TE.ID_ARABICDARIJAENTRY = AR.ID_ARABICDARIJAENTRY
	WHERE TE.TextEntity_Type = 'POSITIVE' OR TE.TextEntity_Type = 'SUPPORT'

	SELECT 
	COUNT(*) COUNTNEGATIVENER from T_ARABICDARIJAENTRY AR
	INNER JOIN T_ARABICDARIJAENTRY_TEXTENTITY TE ON TE.ID_ARABICDARIJAENTRY = AR.ID_ARABICDARIJAENTRY
	WHERE TE.TextEntity_Type = 'NEGATIVE' OR TE.TextEntity_Type = 'EXPLETIVE' OR TE.TextEntity_Type = 'OPPOSE'